
- alias: "Start room 1 roller shutter up"
  variables:
    is_relay_off: '{{ is_state("binary_sensor.unio_relay_1", "off") }}'
  trigger:
    - platform: state
      entity_id: input_button.relay1
  action:
    - service: mqtt.publish
      data:
        topic: "/control/o1"
        payload: "0"
    - service: mqtt.publish
      data:
        topic: "/control/o2"
        payload: "0"
    - condition: "{{ is_relay_off }}"
    - service: mqtt.publish
      data:
        topic: "/control/o1"
        payload: "5s"

- alias: "Start room 1 roller shutter down"
  variables:
    is_relay_off: '{{ is_state("binary_sensor.unio_relay_2", "off") }}'
  trigger:
    - platform: state
      entity_id: input_button.relay2
  action:
    - service: mqtt.publish
      data:
        topic: "/control/o1"
        payload: "0"
    - service: mqtt.publish
      data:
        topic: "/control/o2"
        payload: "0"
    - condition: "{{ is_relay_off }}"
    - service: mqtt.publish
      data:
        topic: "/control/o2"
        payload: "5s"

- alias: "Start room 2 roller shutter up"
  variables:
    is_relay_off: '{{ is_state("binary_sensor.unio_relay_3", "off") }}'
  trigger:
    - platform: state
      entity_id: input_button.relay3
  action:
    - service: mqtt.publish
      data:
        topic: "/control/o3"
        payload: "0"
    - service: mqtt.publish
      data:
        topic: "/control/o4"
        payload: "0"
    - condition: "{{ is_relay_off }}"
    - service: mqtt.publish
      data:
        topic: "/control/o3"
        payload: "8s"

- alias: "Start room 2 roller shutter down"
  variables:
    is_relay_off: '{{ is_state("binary_sensor.unio_relay_4", "off") }}'
  trigger:
    - platform: state
      entity_id: input_button.relay4
  action:
    - service: mqtt.publish
      data:
        topic: "/control/o3"
        payload: "0"
    - service: mqtt.publish
      data:
        topic: "/control/o4"
        payload: "0"
    - condition: "{{ is_relay_off }}"
    - service: mqtt.publish
      data:
        topic: "/control/o4"
        payload: "8s"
