title: Home
views:
  - path: default_view
    title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: binary_sensor.unio_relay_1
                name: Relay 1
                state_color: true
              - entity: binary_sensor.unio_relay_2
                name: Relay 2
                state_color: true
              - entity: binary_sensor.unio_relay_3
                name: Relay 3
                state_color: true
              - entity: binary_sensor.unio_relay_4
                name: Relay 4
                state_color: true
            title: Relay status
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: input_button.relay1
                    name: Up
                  - entity: input_button.relay2
                    name: Down
                title: Room-1 shutter
              - type: entities
                entities:
                  - entity: input_button.relay3
                    name: Up
                  - entity: input_button.relay4
                    name: Down
                title: Room-2 shutter
