title: Home
views:
  - path: default_view
    title: Home
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.unio_relay_1
            name: Relay 1
            state_color: true
          - entity: binary_sensor.unio_relay_2
            name: Relay 2
            state_color: true
          - entity: binary_sensor.unio_relay_3
            name: Relay 3
            state_color: true
          - entity: binary_sensor.unio_relay_4
            name: Relay 4
            state_color: true
        title: Relay status
      - type: entities
        entities:
          - entity: input_datetime.irrigation_start_time
            name: Start time
          - entity: input_number.irrigation_relay_min
            name: Run time in minutes
        title: Irrigation control
